//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEMS3_GSApp.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class IBOBTran
    {
        public int TransactionId { get; set; }
        public string EventType { get; set; }
        public string ITRNumber { get; set; }
        public string DummyITRNumber { get; set; }
        public string TwoDPin { get; set; }
        public string RFID { get; set; }
        public string Barcode { get; set; }
        public string OldBarcode { get; set; }
        public string ScanningType { get; set; }
        public Nullable<int> UserId { get; set; }
        public System.DateTime ActivityDate { get; set; }
        public string DepotLoc { get; set; }
        public string DeviceName { get; set; }
        public string IbcType { get; set; }
        public string ContainerNumber { get; set; }
        public bool SapSendStatus { get; set; }
        public Nullable<System.DateTime> SapSendTime { get; set; }
        public string SapSyncStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeletedSyncStatus { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string SapUniqueKey { get; set; }
        public Nullable<bool> IsModifiedSyncStatus { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsModified { get; set; }
        public string InputType { get; set; }
        public Nullable<int> TransId_LS { get; set; }
        public string LS_Name { get; set; }
        public Nullable<bool> Approval { get; set; }
        public Nullable<bool> IsCreated { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
        public Nullable<System.DateTime> GenericDate_LS { get; set; }
        public string itrBinType { get; set; }
        public string prevITRNumber { get; set; }
        public string prevEvent { get; set; }
        public string prevOneDBarcode { get; set; }
        public Nullable<int> ApprovalTypeId { get; set; }
        public Nullable<int> TagExceptionTypeId { get; set; }
    }
}
