//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEMS3_GSApp.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag_Details
    {
        public int TagDetailsID { get; set; }
        public string PONumber { get; set; }
        public string Barcode { get; set; }
        public string RFID { get; set; }
        public string TagEPC { get; set; }
        public string TagTID { get; set; }
        public string ETSI_QI { get; set; }
        public string FCC_QI { get; set; }
        public string JPN_QI { get; set; }
        public string BoxNo { get; set; }
    }
}
