//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEMS3_GSApp.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagAssignment
    {
        public int TagId { get; set; }
        public string DepotLoc { get; set; }
        public string IBCType { get; set; }
        public string TwoDBarcode { get; set; }
        public string RFID { get; set; }
        public string OneDBarcode { get; set; }
        public Nullable<int> UserId { get; set; }
        public System.DateTime ActivityDate { get; set; }
        public Nullable<int> IsRetagging { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string DeviceName { get; set; }
        public Nullable<int> RetaggingCount { get; set; }
        public Nullable<int> TagId_LS { get; set; }
        public string LS_Name { get; set; }
        public Nullable<bool> IsCreated { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
        public Nullable<System.DateTime> GenericDate_LS { get; set; }
        public string FirstPrevious1D { get; set; }
        public string FirstPrevious2D { get; set; }
        public string SecondPrevious1D { get; set; }
        public string SecondPrevious2D { get; set; }
        public Nullable<int> FirstOldBinTypeId { get; set; }
        public Nullable<int> SecondOldBinTypeId { get; set; }
    }
}
